name: build_windows

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run pack:prepare
    - run: npm run pack:win:publish
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
